### ISSUE TITLE
Interpret scientific name and taxonomy fields using the new name matching service

### ISSUE THREAD

**Issue by asturcon** [gbif/pipelines#18]
current interpreter: https://github.com/gbif/occurrence/blob/master/occurrence-processor/src/main/java/org/gbif/occurrence/processor/interpreting/TaxonomyInterpreter.java

**Subtasks:**
- [x] Basic interpreter and structure
- [x] Move taxonomy interpretation to gbif module
- [x] Use new FP classes in taxonomy interpretation

**Comment by asturcon** [comment]
Diagram with the taxonomic interpretation implemented in this issue:
![taxonomy interpretation diagram](https://user-images.githubusercontent.com/25691745/35799176-3d7ad938-0a65-11e8-9943-0886ca26879b.png)

@fmendezh should we do something else besides adding an Issue when the match type is NONE? In the old interpretation they set the kingdom to unknown, but we're following a different approach since we just serialize the WS response to an Avro file. I'm not sure about the implications.

I also add a diagram with the rank interpretation that I used in development to understand the process (it's the same interpretation as the old one):
![interpret rank diagram](https://user-images.githubusercontent.com/25691745/35798217-638c0320-0a62-11e8-8345-a61099b594a4.png)
