### ISSUE TITLE
Milestone 1: Datasets available as Avro

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#57]
On completion of this milestone all datasets will be converted into `ExtendedRecord` format and available on the HDFS filesystem as `Avro` files.  Event subscribers listening on each environment messaging bus (dev,uat,production) will follow changes due to ongoing crawling and new dataset publications.  Care will be taken to ensure that the libraries used to convert formats could potentially be reused in another platform which does not have GBIF messaging and HDFS dependencies.

Encompasses the following major tasks:

- [x] #49 Add rowType to ExtendedRecord
- [x] #60 ExtendedRecord builder for XML Files 
- [x] #58 Propagate changes in XML based crawling to Avro files
- [x] #59 Propagate changes in DwC-A based crawling to Avro files
- [x] #61 Release and deploy `crawler-cli` 
- [x] #62 Develop and execute script to import all datasets to HDFS

**Comment by muttcg** [comment]
Outdated
