### ISSUE TITLE
ExtendedRecord builder for XML files

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#60]
Production crawling of datasets registered using XML protocols (described in #58) produces a series of XML files on a file system.
We wish to have a builder that can take a nested directory of XML files as input and convert those into an Avro File of `ExtendedRecord` (e.g. along the lines of `ExtendedRecords.convertFromXML(Path inputDir, OutputStream target)`.   This needs to support DiGIR, TAPIR and ABCD formats.

The XML handling for this is already done, tried and tested in the following:
  1. The [OccurrenceParser](https://github.com/gbif/occurrence/blob/master/occurrence-parser/src/main/java/org/gbif/occurrence/OccurrenceParser.java#L82) converts a response page of XML into individual XML records (known as "fragments")
  2. The [XMLFragmentParser](https://github.com/gbif/occurrence/blob/master/occurrence-parser/src/main/java/org/gbif/occurrence/parsing/xml/XmlFragmentParser.java) takes those records and converts them into objects

@fmendezh and I agree that we do not wish to introduce dependencies on any `occurrence/*` modules in the pipelines project.  Instead we propose that a new `xml-occurrence-parsers` be created as a module in the `pipelines` project and the relevant code and tests be copied and relocated to a new package.  Please note that a significant amount of effort has already been invested in the XML Digester based parsing and should be reused. 

An added complexity here is that due to the nature of crawling the XML files will hold duplicate records.  This process must remove the duplicates, using the same mechanism [as used currently](https://github.com/gbif/occurrence/blob/master/occurrence-parser/src/main/java/org/gbif/occurrence/parsing/xml/XmlFragmentParser.java#L150) - this will surely raise questions to be answered during implementation.  In removing duplicates we must recognise that we wish to run minimal memory requirements (100s MB only) and therefore need a mechanism to handle this without introducing a dependency on an external technology.  Something along the lines of [mapdb](http://www.mapdb.org/) which GBIF use in Checklist indexing to good effect would be sensible as an embedded option.

This blocks #58 

Related tasks:
- [x] #64 Move occurrence-parsers to pipelines/xml-occurrence-parsers
- [x] #68 Convert XML (BioCASe, DiGIR and TAPIR) records to ExtendedRecord/Avro 
- [x]  #69 Duplicate XML records detection
