### ISSUE TITLE
Implement AVRO schemas and beam transforms for prototype extended data model 

### ISSUE THREAD

**Issue by djtfmartin** [gbif/pipelines#694]
This is an epic to help track the implementation of the prototype extended data model in pipelines.
The more detailed prototype model with fields is here (developed by @charvolant):
https://user-images.githubusercontent.com/444897/159949918-18f7e168-ce82-45ea-8aca-eb0d18b1bba4.svg

## New AVRO schemas

New AVRO schemas are required for the following entities:
* `Occurrence` - the [`BasicRecord` AVRO schema](https://github.com/gbif/pipelines/blob/dev/sdks/models/src/main/avro/core/basic-record.avsc) is roughly the equivalent of an `Occurrence` entity in the new extended data model.  Suggest this is used as a starting point, but it also needs to support references to the [`EventCoreRecord `](https://github.com/gbif/pipelines/blob/682_skeleton_event_based_data/sdks/models/src/main/avro/core/event-core-record.avsc). 
* `ExtendedMeasurementOrFact` - possibly 2 schemas,  1 for quantitative and 1 for qualitative assertions

The current [`EventCoreRecord ` AVRO schema](https://github.com/gbif/pipelines/blob/682_skeleton_event_based_data/sdks/models/src/main/avro/core/event-core-record.avsc) should suffice to contain the dataset information associated with the event in a denormalized fashion.

The [`Multimedia` AVRO schema ](https://github.com/gbif/pipelines/blob/dev/sdks/models/src/main/avro/extension/multimedia-record.avsc) can be reused in the event pipelines.

## Tasks
- [x] Add proposal for `eventType` as a new term to DwC (@tucotuco)
- [x] Add `eventType` to to Event schema for DwC-A in the rs.gbif.org namespace (@timrobertson100)
- [x] [Define initial `eventType` vocabulary](https://github.com/gbif/vocabulary/issues/107) (@charvolant)
- [x] Additional fields to be added to [Event core record AVRO schema](https://github.com/gbif/pipelines/blob/682_skeleton_event_based_data/sdks/models/src/main/avro/core/event-core-record.avsc) including `eventType`
- [x] Implementation of `Occurrence` AVRO schema 
- [x] Implementation of `ExtendedMeasurementOrFact` AVRO schema

**Comment by charvolant** [comment]
On the whole, I don't think we'll need to do much in the way of special AVROness. My suggestion is that Survey, SiteVisit, Sample, Observation etc. are all rolled into a common event schema with an eventType and some validation rules on how parent and child events hang together.

Similarly, I expect whatever is in Occurrence to be handled the same way that occurrences are handled in the current pipeline.

I'm not sure about ExtendedMeasurementOrFact. I'm looking through the pipelines trying to work out whether they can be easily attached to event or to an occurrence record but I believe that this is already done.

The major difficulty that I foresee is percolating information down the event hierarchy and out to occurrences. It looks like an iterative process.

**Comment by tucotuco** [comment]
Just quickly because I have to head out for another day in the field, The summary @timrobertson100 gave in the previous comment looks right on target.

**Comment by timrobertson100** [comment]
There is now a [proposal](https://github.com/tdwg/dwc/issues/408) `eventType` in DwC

**Comment by timrobertson100** [comment]
The schema registry sandbox now has [event core](https://rs.gbif.org/sandbox/core/dwc_event_2022-04-04.xml) with `eventType` term. The https://ipt.gbif.org/ installation used for testing has this updated for use. I will inform the Humboldt task group, who are similarly preparing test datasets while testing [their extension](https://rs.gbif.org/sandbox/extension/Humboldt_2022-03-02.xml). If we have any example datasets, that are OK to go on public URLs while we explore this, please ping me and I can load them into the test IPT.

**Comment by rubenpp7** [comment]
Hi @timrobertson100 

You can explore http://ipt.gbif.pt/ipt/resource.do?r=benthic-alentejo-2011 . Currently this dataset documents its event hierarchy type using the "type" field (common practice in EurOBIS datasets due to the lack of a better fitting DwC term). Ideally, the information in this field ("sample", "station", "cruise") should be moved to the new eventType field.

Please let me know if this example dataset fits your purpose :)

**Comment by timrobertson100** [comment]
Thank you @rubenpp7 - we had wondered if anyone was doing this already. We'll look at that.

**Comment by ymgan** [comment]
Hey Tim, Ruben, thank you two so much for this!! 
I just wanted to leave this issue and the paper here because using the "type" field has been around since 2017 and I thought it could be interesting for the use case:

https://github.com/iobis/env-data/issues/4
http://bdj.pensoft.net/articles.php?id=10989&instance_id=3385375

**Comment by djtfmartin** [comment]
This is old issue created at the start of the project.
It has been split into several more specific issues.  Marking as done.
