### ISSUE TITLE
Milestone 2: Datasets interpreted into Avro

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#90]
On completion of this milestone all datasets will be interpreted into a series of avro files available on the HDFS. When a new `ExtendedRecord` is saved, a message will go out to RabbitMQ broadcasting the new file availability. Event subscribers listening on each environment messaging bus (dev,uat,production) will follow this feed and trigger an interpretation beam pipeline. Once interpreted a new message will be broadcast notifying that the files are available. This will be deployed on dev, uat and production to follow the live feed.  A script will be available to trigger a re-interpretation of one or all datasets - this is needed as we'll be rapidly evolving the interpretation pipeline and will want to reprocess each. 

It should be possible to reinterpret e.g. only the taxonomy, or the geographic component of the dataset. 

Small dataset interpretations should not use cluster resources - large ones should.  This should be determined by the input filesize and be configurable (approx 100,000 records of a typical schema seems appropriate). 

Encompasses the following major tasks:

- [ ] Broadcast message on `ExtendedRecord` file change
- [ ] Trigger pipeline processing (Direct / Spark runner based on filesize)
- [ ] Pipeline architecture (noting criteria to e.g. support a re-interpret only taxonomy)
- [ ] Broadcast message on completion
- [ ] Script to trigger all interpretations
- [ ] Test on dev, uat
- [ ] Release crawler and pipelines
- [ ] Deploy production (including nagios)
- [ ] Execute an interpretion of all dataset
